/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx_gpio_driver.h"

void delay()
{
	for (uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
	// Configure LED
	// Minimum configuration necessary for timed toggle
	GPIO_Handle_t GpioLed;
	GpioLed.pGPIOx = GPIOA;
	GpioLed.pGPIOx_pin.GPIO_PinNumber = 5;
	GpioLed.pGPIOx_pin.GPIO_PinMode = GPIO_MODE_OUT;

	// Initializes configuration parameters
	GPIO_Init(&GpioLed);

	for(;;) {
		GPIO_ToggleOutputPin(GpioLed.pGPIOx, GpioLed.pGPIOx_pin.GPIO_PinNumber);
		delay();
	}

	return 0;
}





